import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "bn";

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  function t(key: string): string {
    const dict = lang === "bn" ? bn : en;
    return (dict as any)[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─── English ─────────────────────────────────────────────────────────────────
const en: Record<string, string> = {
  // Nav
  nav_dashboard: "Dashboard",
  nav_fleet: "Fleet",
  nav_routes: "Routes & Trips",
  nav_drivers: "Drivers",
  nav_tickets: "Tickets & Revenue",
  nav_counters: "Counters",
  nav_reports: "Reports",
  nav_settings: "Settings",
  nav_pos: "POS Terminal",
  nav_fleet_owner: "Fleet Owner",

  // Demo Banner
  screen_dashboard: "Screen 1 — Operations Dashboard",
  screen_pos: "Screen 2 — Counter POS",
  screen_vehicle: "Screen 3 — Vehicle Detail",
  screens_label: "SCREENS:",

  // TopBar
  good_morning: "Good morning",
  good_afternoon: "Good afternoon",
  good_evening: "Good evening",
  search_placeholder: "Search buses, routes, drivers...",
  pos_terminal: "POS Terminal",
  language_toggle: "বাং",

  // Page Titles
  page_dashboard: "Operations Dashboard",
  page_fleet: "Fleet Management",
  page_routes: "Routes & Trips",
  page_drivers: "Drivers",
  page_tickets: "Tickets & Revenue",
  page_counters: "Counters",
  page_reports: "Reports",
  page_settings: "Settings",
  page_vehicle_detail: "Vehicle Detail",

  // KPIs
  kpi_active_buses: "Active Buses",
  kpi_active_buses_sub: "idle today",
  kpi_revenue: "Today's Revenue",
  kpi_revenue_trend: "+12% vs yesterday",
  kpi_tickets: "Tickets Sold Today",
  kpi_tickets_trend: "+24 vs yesterday",
  kpi_ontime: "On-Time Departure",
  kpi_ontime_sub: "Below 90% threshold",
  kpi_ontime_badge: "↓ Below target",
  kpi_active_badge: "Active",

  // Map
  live_fleet_map: "Live Fleet Map",
  on_time: "On Time",
  delayed: "Delayed",
  idle: "Idle",
  live: "Live",

  // Trips table
  todays_trips: "Today's Trips",
  col_route: "Route",
  col_depart: "Depart.",
  col_bus: "Bus",
  col_status: "Status",
  col_load: "Load",
  status_on_time: "On Time",
  status_delayed: "Delayed",
  status_departed: "Departed",
  status_arrived: "Arrived",

  // Revenue chart
  revenue_7days: "Revenue — Last 7 Days",
  revenue_sub: "Daily ticket revenue in BDT",
  revenue_trend: "+8.3% this week",

  // Compliance
  compliance_alerts: "Compliance Alerts",
  compliance_critical: "Critical",
  col_bus_num: "Bus #",
  col_document: "Document",
  col_expiry: "Expiry",
  col_days: "Days",
  col_action: "Action",
  action_renew: "Renew",

  // Fleet
  fleet_title: "Fleet Management",
  fleet_registered: "vehicles registered",
  fleet_active: "active today",
  btn_filter: "Filter",
  btn_add_vehicle: "Add Vehicle",
  search_fleet: "Search by bus ID, model, driver...",
  col_bus_id: "Bus ID",
  col_registration: "Registration",
  col_model: "Model",
  col_driver: "Driver",
  col_compliance: "Compliance",
  col_last_trip: "Last Trip",

  // Vehicle Detail
  back_fleet: "Fleet",
  bus_label: "Bus #",
  status_active: "● Active",
  registration: "Registration",
  route_label: "Dhaka–Chittagong Route",
  btn_set_reminder: "Set Reminder",
  btn_upload_doc: "Upload Document",
  stat_model: "Model",
  stat_type: "Type",
  stat_capacity: "Capacity",
  stat_route: "Route",
  stat_total_km: "Total KM",
  stat_in_service: "In Service Since",
  tab_overview: "Overview",
  tab_trip_history: "Trip History",
  tab_documents: "Documents",
  tab_maintenance: "Maintenance",
  tab_driver_log: "Driver Log",
  revenue_5weeks: "Revenue — Last 5 Weeks",
  quick_stats: "Quick Stats",
  stat_total_trips: "Total Trips (2026)",
  stat_avg_load: "Avg Load Factor",
  stat_ontime_rate: "On-Time Rate",
  stat_total_revenue: "Total Revenue (2026)",
  stat_incidents: "Incidents",
  col_trip_id: "Trip ID",
  col_date: "Date",
  col_arrive: "Arrive",
  col_revenue: "Revenue",
  col_issue_date: "Issue Date",
  col_expiry_date: "Expiry Date",
  col_doc_status: "Status",
  btn_upload_renewal: "Upload Renewal",
  btn_upload_now: "Upload Now",
  btn_view: "View",
  doc_expired: "Expired",
  doc_lifetime: "Valid (Lifetime)",
  doc_valid: "Valid",
  doc_expires_in: "Expires in",
  days_label: "days",
  col_service_type: "Service Type",
  col_technician: "Technician",
  col_cost: "Cost",
  col_trip: "Trip",
  col_duration: "Duration",
  col_rating: "Rating",

  // POS
  pos_back: "Dashboard",
  pos_counter: "Sayedabad Counter",
  pos_agent: "Agent:",
  pos_online: "Online",
  pos_shift: "Shift:",
  pos_trip_selection: "Trip Selection",
  pos_departure_times: "DEPARTURE TIMES",
  pos_full: "FULL",
  pos_seats: "seats",
  pos_seat_map: "Seat Map",
  pos_seats_layout: "44 seats (2+2 layout)",
  pos_available: "Available",
  pos_booked: "Booked",
  pos_selected: "Selected",
  pos_reserved: "Reserved",
  pos_driver_seat: "🚘 Driver's Seat",
  pos_click_hint: "Click a white seat to select",
  pos_booking_summary: "Booking Summary",
  pos_seat_s: "seat",
  pos_seats_s: "seats",
  pos_passenger_info: "Passenger Info",
  pos_full_name: "Full Name",
  pos_mobile: "Mobile number",
  pos_seats_selected: "SEATS SELECTED",
  pos_none_selected: "None selected",
  pos_fare_breakdown: "Fare Breakdown",
  pos_base_fare: "Base Fare / Seat",
  pos_seats_x: "Seats",
  pos_service_fee: "Service Fee",
  pos_total: "TOTAL",
  pos_payment_method: "Payment Method",
  pos_issue_tickets: "Issue Tickets",
  pos_cancel: "Cancel",
  pos_select_seats_first: "Please select seats first",
  pos_issued_title: "Tickets Issued!",
  pos_issued_subtitle: "Transaction complete. Print or send via SMS.",
  pos_btn_print: "🖨 Print Receipt",
  pos_btn_sms: "📱 Send SMS",
  pos_route: "Route",
  pos_date: "Date",
  pos_departure: "Departure",
  pos_bus: "Bus #",

  // Routes page
  routes_title: "Routes & Trips",
  routes_sub: "routes configured",
  routes_trips_today: "trips scheduled today",
  btn_add_route: "Add Route",
  col_route_name: "Route",
  col_origin: "Origin",
  col_destination: "Destination",
  col_distance: "Distance",
  col_buses: "Buses",
  col_daily_trips: "Daily Trips",
  col_avg_fare: "Avg Fare",
  route_detail: "Route Detail",
  today_schedule: "Today's Schedule",

  // Drivers page
  drivers_title: "Drivers",
  drivers_sub: "drivers registered",
  btn_add_driver: "Add Driver",
  search_drivers: "Search drivers...",
  col_name: "Name",
  col_phone: "Phone",
  col_license: "License Expiry",
  col_trips_month: "Trips/Month",
  col_assigned_route: "Assigned Route",
  driver_active: "Active",
  driver_on_leave: "On Leave",
  driver_inactive: "Inactive",
  col_driver_id: "Driver ID",

  // Tickets page
  tickets_title: "Tickets & Revenue",
  total_revenue_today: "Total Revenue Today",
  tickets_sold_today: "Tickets Sold Today",
  avg_ticket_value: "Avg Ticket Value",
  refund_rate: "Refund Rate",
  recent_transactions: "Recent Transactions",
  col_ticket_id: "Ticket #",
  col_passenger: "Passenger",
  col_departure_time: "Departure",
  col_payment: "Payment",
  col_amount: "Amount",
  payment_cash: "Cash",
  payment_bkash: "bKash",
  payment_nagad: "Nagad",
  revenue_by_route: "Revenue by Route",

  // Counters page
  counters_title: "Counters",
  counters_sub: "counter locations active",
  btn_add_counter: "Add Counter",
  col_counter_name: "Counter",
  col_location: "Location",
  col_agent: "Agent",
  col_today_sales: "Today's Sales",
  col_today_tickets: "Tickets Today",
  counter_online: "Online",
  counter_offline: "Offline",

  // Reports page
  reports_title: "Reports",
  btn_export_pdf: "Export PDF",
  btn_export_csv: "Export CSV",
  monthly_revenue: "Monthly Revenue (2026)",
  route_performance: "Route Performance",
  fleet_utilization: "Fleet Utilization",
  compliance_summary: "Compliance Summary",
  total_documents: "Total Documents",
  valid_docs: "Valid",
  expiring_docs: "Expiring Soon",
  expired_docs: "Expired",

  // Settings page
  settings_title: "Settings",
  settings_company: "Company Info",
  settings_notifications: "Notifications",
  settings_security: "Security",
  settings_language: "Language & Region",
  company_name: "Company Name",
  company_name_val: "Dhaka Express Bus Services Ltd.",
  company_reg: "Company Registration",
  company_reg_val: "RJSC-2018-0042891",
  company_address: "Address",
  company_address_val: "42 Motijheel C/A, Dhaka-1000, Bangladesh",
  company_phone: "Phone",
  company_email: "Email",
  btn_save: "Save Changes",
  notif_compliance: "Compliance Alerts",
  notif_compliance_sub: "Get notified before documents expire",
  notif_trip: "Trip Updates",
  notif_trip_sub: "Real-time trip status notifications",
  notif_revenue: "Daily Revenue Report",
  notif_revenue_sub: "End-of-day revenue summary",
  notif_sms: "SMS Notifications",
  notif_sms_sub: "Send ticket confirmations via SMS",
  lang_select: "Display Language",
  lang_en: "English",
  lang_bn: "বাংলা (Bangla)",
  currency_format: "Currency Format",
  date_format: "Date Format",
  timezone: "Timezone",
  security_change_pass: "Change Password",
  security_2fa: "Two-Factor Authentication",
  security_2fa_sub: "Add an extra layer of security",
  security_sessions: "Active Sessions",
  security_sessions_sub: "Manage logged-in devices",
};

// ─── Bangla ──────────────────────────────────────────────────────────────────
const bn: Record<string, string> = {
  // Nav
  nav_dashboard: "ড্যাশবোর্ড",
  nav_fleet: "বহর",
  nav_routes: "রুট ও ট্রিপ",
  nav_drivers: "চালক",
  nav_tickets: "টিকেট ও আয়",
  nav_counters: "কাউন্টার",
  nav_reports: "রিপোর্ট",
  nav_settings: "সেটিংস",
  nav_pos: "POS টার্মিনাল",
  nav_fleet_owner: "বহর মালিক",

  // Demo Banner
  screen_dashboard: "স্ক্রিন ১ — অপারেশন ড্যাশবোর্ড",
  screen_pos: "স্ক্রিন ২ — কাউন্টার POS",
  screen_vehicle: "স্ক্রিন ৩ — যানবাহন বিবরণ",
  screens_label: "স্ক্রিন:",

  // TopBar
  good_morning: "শুভ সকাল",
  good_afternoon: "শুভ অপরাহ্ন",
  good_evening: "শুভ সন্ধ্যা",
  search_placeholder: "বাস, রুট, চালক খুঁজুন...",
  pos_terminal: "POS টার্মিনাল",
  language_toggle: "EN",

  // Page Titles
  page_dashboard: "অপারেশন ড্যাশবোর্ড",
  page_fleet: "বহর ব্যবস্থাপনা",
  page_routes: "রুট ও ট্রিপ",
  page_drivers: "চালক",
  page_tickets: "টিকেট ও আয়",
  page_counters: "কাউন্টার",
  page_reports: "রিপোর্ট",
  page_settings: "সেটিংস",
  page_vehicle_detail: "যানবাহন বিবরণ",

  // KPIs
  kpi_active_buses: "সক্রিয় বাস",
  kpi_active_buses_sub: "আজ অলস",
  kpi_revenue: "আজকের আয়",
  kpi_revenue_trend: "গতকালের তুলনায় +১২%",
  kpi_tickets: "আজ টিকেট বিক্রি",
  kpi_tickets_trend: "গতকালের তুলনায় +২৪",
  kpi_ontime: "সময়মতো প্রস্থান",
  kpi_ontime_sub: "৯০% লক্ষ্যমাত্রার নিচে",
  kpi_ontime_badge: "↓ লক্ষ্যমাত্রার নিচে",
  kpi_active_badge: "সক্রিয়",

  // Map
  live_fleet_map: "লাইভ বহর মানচিত্র",
  on_time: "সময়মতো",
  delayed: "বিলম্বিত",
  idle: "অলস",
  live: "লাইভ",

  // Trips table
  todays_trips: "আজকের ট্রিপ",
  col_route: "রুট",
  col_depart: "প্রস্থান",
  col_bus: "বাস",
  col_status: "অবস্থা",
  col_load: "লোড",
  status_on_time: "সময়মতো",
  status_delayed: "বিলম্বিত",
  status_departed: "প্রস্থান করেছে",
  status_arrived: "পৌঁছেছে",

  // Revenue chart
  revenue_7days: "রাজস্ব — গত ৭ দিন",
  revenue_sub: "দৈনিক টিকেট আয় (টাকায়)",
  revenue_trend: "+৮.৩% এই সপ্তাহে",

  // Compliance
  compliance_alerts: "সম্মতি সতর্কতা",
  compliance_critical: "জরুরি",
  col_bus_num: "বাস নং",
  col_document: "নথি",
  col_expiry: "মেয়াদ",
  col_days: "দিন",
  col_action: "পদক্ষেপ",
  action_renew: "নবায়ন",

  // Fleet
  fleet_title: "বহর ব্যবস্থাপনা",
  fleet_registered: "যানবাহন নিবন্ধিত",
  fleet_active: "আজ সক্রিয়",
  btn_filter: "ফিল্টার",
  btn_add_vehicle: "যানবাহন যোগ করুন",
  search_fleet: "বাস আইডি, মডেল, চালক দিয়ে খুঁজুন...",
  col_bus_id: "বাস আইডি",
  col_registration: "নিবন্ধন",
  col_model: "মডেল",
  col_driver: "চালক",
  col_compliance: "সম্মতি",
  col_last_trip: "শেষ ট্রিপ",

  // Vehicle Detail
  back_fleet: "বহর",
  bus_label: "বাস নং",
  status_active: "● সক্রিয়",
  registration: "নিবন্ধন",
  route_label: "ঢাকা–চট্টগ্রাম রুট",
  btn_set_reminder: "অনুস্মারক সেট করুন",
  btn_upload_doc: "নথি আপলোড",
  stat_model: "মডেল",
  stat_type: "ধরন",
  stat_capacity: "ধারণক্ষমতা",
  stat_route: "রুট",
  stat_total_km: "মোট কিমি",
  stat_in_service: "সেবায় প্রবেশ",
  tab_overview: "সংক্ষিপ্ত বিবরণ",
  tab_trip_history: "ট্রিপ ইতিহাস",
  tab_documents: "নথি",
  tab_maintenance: "রক্ষণাবেক্ষণ",
  tab_driver_log: "চালক লগ",
  revenue_5weeks: "রাজস্ব — গত ৫ সপ্তাহ",
  quick_stats: "দ্রুত পরিসংখ্যান",
  stat_total_trips: "মোট ট্রিপ (২০২৬)",
  stat_avg_load: "গড় লোড ফ্যাক্টর",
  stat_ontime_rate: "সময়মতো হার",
  stat_total_revenue: "মোট আয় (২০২৬)",
  stat_incidents: "ঘটনা",
  col_trip_id: "ট্রিপ আইডি",
  col_date: "তারিখ",
  col_arrive: "আগমন",
  col_revenue: "আয়",
  col_issue_date: "ইস্যু তারিখ",
  col_expiry_date: "মেয়াদ তারিখ",
  col_doc_status: "অবস্থা",
  btn_upload_renewal: "নবায়ন আপলোড",
  btn_upload_now: "এখনই আপলোড",
  btn_view: "দেখুন",
  doc_expired: "মেয়াদোত্তীর্ণ",
  doc_lifetime: "বৈধ (আজীবন)",
  doc_valid: "বৈধ",
  doc_expires_in: "মেয়াদ শেষ",
  days_label: "দিনে",
  col_service_type: "সেবার ধরন",
  col_technician: "প্রযুক্তিবিদ",
  col_cost: "খরচ",
  col_trip: "ট্রিপ",
  col_duration: "সময়কাল",
  col_rating: "রেটিং",

  // POS
  pos_back: "ড্যাশবোর্ড",
  pos_counter: "সায়েদাবাদ কাউন্টার",
  pos_agent: "এজেন্ট:",
  pos_online: "অনলাইন",
  pos_shift: "শিফট:",
  pos_trip_selection: "ট্রিপ নির্বাচন",
  pos_departure_times: "প্রস্থানের সময়",
  pos_full: "পূর্ণ",
  pos_seats: "আসন",
  pos_seat_map: "আসন মানচিত্র",
  pos_seats_layout: "৪৪ আসন (২+২ বিন্যাস)",
  pos_available: "উপলব্ধ",
  pos_booked: "বুকড",
  pos_selected: "নির্বাচিত",
  pos_reserved: "সংরক্ষিত",
  pos_driver_seat: "🚘 চালকের আসন",
  pos_click_hint: "নির্বাচন করতে সাদা আসনে ক্লিক করুন",
  pos_booking_summary: "বুকিং সারসংক্ষেপ",
  pos_seat_s: "আসন",
  pos_seats_s: "আসন",
  pos_passenger_info: "যাত্রীর তথ্য",
  pos_full_name: "পুরো নাম",
  pos_mobile: "মোবাইল নম্বর",
  pos_seats_selected: "নির্বাচিত আসন",
  pos_none_selected: "কোনো আসন নির্বাচিত হয়নি",
  pos_fare_breakdown: "ভাড়ার বিবরণ",
  pos_base_fare: "বেস ভাড়া / আসন",
  pos_seats_x: "আসন সংখ্যা",
  pos_service_fee: "সেবা চার্জ",
  pos_total: "মোট",
  pos_payment_method: "পেমেন্ট পদ্ধতি",
  pos_issue_tickets: "টিকেট ইস্যু করুন",
  pos_cancel: "বাতিল",
  pos_select_seats_first: "প্রথমে আসন নির্বাচন করুন",
  pos_issued_title: "টিকেট ইস্যু হয়েছে!",
  pos_issued_subtitle: "লেনদেন সম্পন্ন। প্রিন্ট করুন বা এসএমএসে পাঠান।",
  pos_btn_print: "🖨 রিসিপ্ট প্রিন্ট",
  pos_btn_sms: "📱 এসএমএস পাঠান",
  pos_route: "রুট",
  pos_date: "তারিখ",
  pos_departure: "প্রস্থান",
  pos_bus: "বাস নং",

  // Routes page
  routes_title: "রুট ও ট্রিপ",
  routes_sub: "রুট কনফিগার করা হয়েছে",
  routes_trips_today: "ট্রিপ আজ নির্ধারিত",
  btn_add_route: "রুট যোগ করুন",
  col_route_name: "রুট",
  col_origin: "উৎস",
  col_destination: "গন্তব্য",
  col_distance: "দূরত্ব",
  col_buses: "বাস",
  col_daily_trips: "দৈনিক ট্রিপ",
  col_avg_fare: "গড় ভাড়া",
  route_detail: "রুট বিবরণ",
  today_schedule: "আজকের সময়সূচি",

  // Drivers page
  drivers_title: "চালক",
  drivers_sub: "চালক নিবন্ধিত",
  btn_add_driver: "চালক যোগ করুন",
  search_drivers: "চালক খুঁজুন...",
  col_name: "নাম",
  col_phone: "ফোন",
  col_license: "লাইসেন্সের মেয়াদ",
  col_trips_month: "ট্রিপ/মাস",
  col_assigned_route: "নির্ধারিত রুট",
  driver_active: "সক্রিয়",
  driver_on_leave: "ছুটিতে",
  driver_inactive: "নিষ্ক্রিয়",
  col_driver_id: "চালক আইডি",

  // Tickets page
  tickets_title: "টিকেট ও আয়",
  total_revenue_today: "আজকের মোট আয়",
  tickets_sold_today: "আজ টিকেট বিক্রি",
  avg_ticket_value: "গড় টিকেট মূল্য",
  refund_rate: "ফেরত হার",
  recent_transactions: "সাম্প্রতিক লেনদেন",
  col_ticket_id: "টিকেট নং",
  col_passenger: "যাত্রী",
  col_departure_time: "প্রস্থান",
  col_payment: "পেমেন্ট",
  col_amount: "পরিমাণ",
  payment_cash: "নগদ",
  payment_bkash: "বিকাশ",
  payment_nagad: "নগদ",
  revenue_by_route: "রুট অনুযায়ী আয়",

  // Counters page
  counters_title: "কাউন্টার",
  counters_sub: "কাউন্টার লোকেশন সক্রিয়",
  btn_add_counter: "কাউন্টার যোগ করুন",
  col_counter_name: "কাউন্টার",
  col_location: "অবস্থান",
  col_agent: "এজেন্ট",
  col_today_sales: "আজকের বিক্রয়",
  col_today_tickets: "আজ টিকেট",
  counter_online: "অনলাইন",
  counter_offline: "অফলাইন",

  // Reports page
  reports_title: "রিপোর্ট",
  btn_export_pdf: "PDF রপ্তানি",
  btn_export_csv: "CSV রপ্তানি",
  monthly_revenue: "মাসিক আয় (২০২৬)",
  route_performance: "রুট কার্যক্ষমতা",
  fleet_utilization: "বহর ব্যবহার",
  compliance_summary: "সম্মতি সারসংক্ষেপ",
  total_documents: "মোট নথি",
  valid_docs: "বৈধ",
  expiring_docs: "শীঘ্রই মেয়াদোত্তীর্ণ",
  expired_docs: "মেয়াদোত্তীর্ণ",

  // Settings page
  settings_title: "সেটিংস",
  settings_company: "কোম্পানির তথ্য",
  settings_notifications: "বিজ্ঞপ্তি",
  settings_security: "নিরাপত্তা",
  settings_language: "ভাষা ও অঞ্চল",
  company_name: "কোম্পানির নাম",
  company_name_val: "ঢাকা এক্সপ্রেস বাস সার্ভিসেস লিমিটেড",
  company_reg: "কোম্পানি নিবন্ধন",
  company_reg_val: "RJSC-2018-0042891",
  company_address: "ঠিকানা",
  company_address_val: "৪২ মতিঝিল C/A, ঢাকা-১০০০, বাংলাদেশ",
  company_phone: "ফোন",
  company_email: "ইমেইল",
  btn_save: "পরিবর্তন সংরক্ষণ করুন",
  notif_compliance: "সম্মতি সতর্কতা",
  notif_compliance_sub: "নথির মেয়াদ শেষের আগে সতর্কতা পান",
  notif_trip: "ট্রিপ আপডেট",
  notif_trip_sub: "রিয়েল-টাইম ট্রিপ স্ট্যাটাস বিজ্ঞপ্তি",
  notif_revenue: "দৈনিক আয় রিপোর্ট",
  notif_revenue_sub: "দিনের শেষে আয়ের সারসংক্ষেপ",
  notif_sms: "এসএমএস বিজ্ঞপ্তি",
  notif_sms_sub: "এসএমএসের মাধ্যমে টিকেট নিশ্চিতকরণ পাঠান",
  lang_select: "প্রদর্শন ভাষা",
  lang_en: "ইংরেজি (English)",
  lang_bn: "বাংলা",
  currency_format: "মুদ্রার বিন্যাস",
  date_format: "তারিখের বিন্যাস",
  timezone: "সময় অঞ্চল",
  security_change_pass: "পাসওয়ার্ড পরিবর্তন",
  security_2fa: "দ্বি-স্তরীয় যাচাইকরণ",
  security_2fa_sub: "অতিরিক্ত নিরাপত্তা স্তর যোগ করুন",
  security_sessions: "সক্রিয় সেশন",
  security_sessions_sub: "লগইন করা ডিভাইস পরিচালনা করুন",
};
